<Project Sdk="Microsoft.NET.Sdk">
 
  <PropertyGroup>
    <!-- <OutputType>WinExe</OutputType> -->
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
 
  <ItemGroup>
    <!-- Use the same or newer major version than the one your lazer build ships with -->
    <PackageReference Include="Realm" Version="20.1.0" />
  </ItemGroup>
 
  <ItemGroup>
    <None Update="config.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
 